name: "CliffWorld4x12Determ"
seeds: 1 # Number of seeds to run
env: "CliffWorld4x12Determ" #"LavaWorld13x15Determ" # "LavaWorld13x15StochMovement" # 
policy: "EpsilonGreedy" # ["EpsilonGreedy"]
epsilon_0: .1      # starting value of epsilon eps_0
epsilon_decay: 0.9  # this is parameter beta in eps = eps_0 / n(s)^beta. If beta = 0 we have a fixed epsilon
alpha_0: .1        # starting value of alpha
alpha_decay: 0.    # parameter omega in alpha = alpha / n(s,a)^omega. If omega = 0 we have a fixed alpha
gamma: 1
num_iter: 1000
metric_names: ["episode_returns","episode_lengths"] 